# Generated by Django 4.0.5 on 2022-07-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='static/s_app/img/default.jpg', upload_to='s_app/img/'),
        ),
    ]
